name: Greetings

on:
  issues:
    types: [opened,reopened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '_\('
          label_marker_end: '\)_'

      - name: Show parsed data JSON
        run: |
          echo '${{ steps.parse.outputs.payload }}'
