name: Template

on:
  issues:
    types: [opened,reopened]

jobs:
  template:
    if: contains(github.event.issue.labels.*.name, 'template')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      data: ${{ steps.data.outputs.result }}
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '_\('
          label_marker_end: '\)_'

      - name: Transform input
        id: data
        uses: actions/github-script@v5
        with:
          script: |
            const data = ${{ steps.parse.outputs.payload }};
            const prefix = data.code || data.team;
            data.repo_name = prefix + "-" + data.name;
            data.publish = Object.values(data.publish)[0];
            data.labels = ${{ github.event.issue.labels.*.name }};
            return data;

      - name: Show processes data JSON
        run: |
          echo '${{ steps.data.outputs.result }}'

  publish:
    needs: [template]
    if: needs.template.outputs.data.publish
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo 'I would publish with ${{ needs.template.outputs.data }}'
